// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShopFresh.Data;

#nullable disable

namespace WebShopFresh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.AddressModels.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Created = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "100",
                            Street = "Maksimirska",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        });
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.CategoryModels.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6052),
                            Description = "Test description",
                            Name = "Test kategorija",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 2L,
                            Created = new DateTime(2025, 3, 10, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6098),
                            Description = "Electronic devices and accessories",
                            Name = "Electronics",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 3L,
                            Created = new DateTime(2025, 1, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6102),
                            Description = "Books of various genres",
                            Name = "Books",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 4L,
                            Created = new DateTime(2025, 2, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6106),
                            Description = "Men's, Women's, and Children's clothing",
                            Name = "Clothing",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 5L,
                            Created = new DateTime(2024, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6108),
                            Description = "Appliances and gadgets for home use",
                            Name = "Home Appliances",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 6L,
                            Created = new DateTime(2025, 2, 18, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6111),
                            Description = "Toys for children of all ages",
                            Name = "Toys",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        });
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.OrderModels.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrderAddressId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OrderAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.OrderModels.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.ProductModels.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 2L,
                            Created = new DateTime(2025, 3, 15, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6142),
                            Description = "Latest model smartphone with high-end features",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "Smartphone",
                            Price = 999m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 3L,
                            Created = new DateTime(2025, 1, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6149),
                            Description = "A captivating science fiction novel",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "Science Fiction Novel",
                            Price = 15m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 4L,
                            Created = new DateTime(2025, 2, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6152),
                            Description = "Comfortable cotton t-shirt",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "Men's T-Shirt",
                            Price = 25m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 5L,
                            Created = new DateTime(2024, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6155),
                            Description = "High-efficiency vacuum cleaner",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "Vacuum Cleaner",
                            Price = 150m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6158),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 6L,
                            Created = new DateTime(2025, 3, 10, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6161),
                            Description = "Popular action figure toy",
                            ImageUrl = "/content/action-figure-496wpt-1.jpg",
                            Name = "Action Figure",
                            Price = 30m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 2L,
                            Created = new DateTime(2025, 2, 28, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6163),
                            Description = "High-performance laptop for work and play",
                            ImageUrl = "/content/laptop.jpg",
                            Name = "Laptop",
                            Price = 1200m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 3L,
                            Created = new DateTime(2024, 12, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6166),
                            Description = "An intriguing mystery thriller novel",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "Mystery Thriller",
                            Price = 20m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 4L,
                            Created = new DateTime(2025, 1, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6170),
                            Description = "Stylish and comfortable women's jeans",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "Women's Jeans",
                            Price = 50m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 5L,
                            Created = new DateTime(2023, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6173),
                            Description = "Multi-functional kitchen blender",
                            ImageUrl = "/content/blender.jpg",
                            Name = "Blender",
                            Price = 80m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 6L,
                            Created = new DateTime(2025, 3, 5, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6176),
                            Description = "Creative building blocks for children",
                            ImageUrl = "/content/BuildingBlocks.jpg",
                            Name = "Building Blocks",
                            Price = 40m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6179),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6181),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6184),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1315m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6187),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6190),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6192),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6195),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6198),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6201),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6203),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6206),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6209),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 1L,
                            Created = new DateTime(2025, 3, 20, 15, 30, 9, 505, DateTimeKind.Local).AddTicks(6212),
                            Description = "neki description",
                            ImageUrl = "/content/test-sku.jpg",
                            Name = "TEST",
                            Price = 1525m,
                            Quantity = 0m,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid = true
                        });
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.SessionModels.SessionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SessionItems");
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.UserModel.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebShopFresh.Models.Dbo.UserModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebShopFresh.Models.Dbo.UserModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShopFresh.Models.Dbo.UserModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebShopFresh.Models.Dbo.UserModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.OrderModels.Order", b =>
                {
                    b.HasOne("WebShopFresh.Models.Dbo.UserModel.ApplicationUser", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId");

                    b.HasOne("WebShopFresh.Models.Dbo.AddressModels.Address", "OrderAddress")
                        .WithMany()
                        .HasForeignKey("OrderAddressId");

                    b.Navigation("Buyer");

                    b.Navigation("OrderAddress");
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.OrderModels.OrderItem", b =>
                {
                    b.HasOne("WebShopFresh.Models.Dbo.OrderModels.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("WebShopFresh.Models.Dbo.ProductModels.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.ProductModels.Product", b =>
                {
                    b.HasOne("WebShopFresh.Models.Dbo.CategoryModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.SessionModels.SessionItem", b =>
                {
                    b.HasOne("WebShopFresh.Models.Dbo.UserModel.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.UserModel.ApplicationUser", b =>
                {
                    b.HasOne("WebShopFresh.Models.Dbo.AddressModels.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.CategoryModels.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebShopFresh.Models.Dbo.OrderModels.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
